
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      The target system is: Generic - 4.3.0 - arm
      The host system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/Usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      c:/users/usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:/users/usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib\\libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Users/Usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        C:/ZephyrEMb2/dacMAYBE/debug/CMakeFiles/3.30.0/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: C:/Users/Usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      c:/users/usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:/users/usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib\\libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Users/Usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        C:/ZephyrEMb2/dacMAYBE/debug/CMakeFiles/3.30.0/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1192 (message)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/kernel.cmake:135 (enable_language)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Zephyr/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-zephyr-eabi-gcc.exe (Zephyr SDK 0.17.2) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...

---
events:
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Users/Usuario/.mcuxpressotools/cmake-3.30.0-windows-x86_64/share/cmake-3.30/Modules/CheckCCompilerFlag.cmake:51 (cmake_check_compiler_flag)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/extensions.cmake:2343 (check_c_compiler_flag)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/extensions.cmake:1198 (check_compiler_flag)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/extensions.cmake:2404 (zephyr_check_compiler_flag)"
      - "C:/Zephyr/zephyr/zephyr/cmake/modules/extensions.cmake:164 (target_ld_options)"
      - "C:/Zephyr/zephyr/zephyr/CMakeLists.txt:479 (zephyr_ld_options)"
    directories:
      source: "C:/ZephyrEMb2/dacMAYBE/debug/CMakeFiles/CMakeScratch/TryCompile-7rpwlh"
      binary: "C:/ZephyrEMb2/dacMAYBE/debug/CMakeFiles/CMakeScratch/TryCompile-7rpwlh"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "C:/Zephyr/zephyr/zephyr/cmake/modules"
    buildResult:
      variable: "check_C__nostartfiles__nostdlib__isystem__c__users_usuario_zephyr_sdk_0_17_2_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include___isystem__c__users_usuario_zephyr_sdk_0_17_2_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include_fixed___Wl___unresolved_symbols_ignore_in_object_files__Wl___entry_0__fuse_ld_bfd__mcpu_cortex_m4__mthumb__mabi_aapcs__mfpu_fpv4_sp_d16__mfloat_abi_hard__mfp16_format_ieee__mtp_soft"
      cached: true
      stdout: |
        Change Dir: 'C:/ZephyrEMb2/dacMAYBE/debug/CMakeFiles/CMakeScratch/TryCompile-7rpwlh'
        
        Run Build Command(s): C:/Users/Usuario/.mcuxpressotools/ninja-1.12.1/ninja.exe -v cmTC_df681
        [1/2] C:\\Users\\Usuario\\zephyr-sdk-0.17.2\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gcc.exe -Dcheck_C__nostartfiles__nostdlib__isystem__c__users_usuario_zephyr_sdk_0_17_2_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include___isystem__c__users_usuario_zephyr_sdk_0_17_2_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include_fixed___Wl___unresolved_symbols_ignore_in_object_files__Wl___entry_0__fuse_ld_bfd__mcpu_cortex_m4__mthumb__mabi_aapcs__mfpu_fpv4_sp_d16__mfloat_abi_hard__mfp16_format_ieee__mtp_soft  -nostartfiles -nostdlib -isystem "c:/users/usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include" -isystem "c:/users/usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include-fixed" -Wl,--unresolved-symbols=ignore-in-object-files -Wl,--entry=0 -fuse-ld=bfd -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mfp16-format=ieee -mtp=soft -o CMakeFiles/cmTC_df681.dir/src.c.obj -c C:/ZephyrEMb2/dacMAYBE/debug/CMakeFiles/CMakeScratch/TryCompile-7rpwlh/src.c
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Users\\Usuario\\zephyr-sdk-0.17.2\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gcc.exe -nostartfiles -nostdlib -isystem "c:/users/usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include" -isystem "c:/users/usuario/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include-fixed" -Wl,--unresolved-symbols=ignore-in-object-files -Wl,--entry=0 -fuse-ld=bfd -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mfp16-format=ieee -mtp=soft  CMakeFiles/cmTC_df681.dir/src.c.obj -o cmTC_df681   && cd ."
        
      exitCode: 0
...
